sudo: required
services:
  - docker
  - angular


before_install:
  - docker build . -t bigiayomide/docker-angular -f Dockerfile.dev


script:
  - docker run bigiayomide/docker-angular ng test --watch=false --no-progress
