FROM node:alpine as builder

WORKDIR /app

COPY ./package.json ./

RUN npm install 

RUN npm install -g @angular/cli

COPY ./ ./   

RUN ng build --aot


FROM nginx 

COPY --from=builder /app/dist/multi-build-app /usr/share/html